/**
 * Created by minjie on 4/26/15.
 */
var langs = [
    {text : "Plain Text"},
    {Cucumber : "Gherkin"},
    {abap : "ABAP"},
    {ada : "Ada"},
    {ahk : "autohotkey"},
    {antlr : "ANTLR"},
    {antlr_as : "ANTLR With ActionScript Target"},
    {antlr_cpp : "ANTLR With CPP Target"},
    {antlr_csharp : "ANTLR With C# Target"},
    {antlr_java : "ANTLR With Java Target"},
    {antlr_objc : "ANTLR With ObjectiveC Target"},
    {antlr_perl : "ANTLR With Perl Target"},
    {antlr_python : "ANTLR With Python Target"},
    {antlr_ruby : "ANTLR With Ruby Target"},
    {apacheconf : "ApacheConf"},
    {applescript : "AppleScript"},
    {as : "ActionScript"},
    {as3 : "ActionScript 3"},
    {aspx_cs : "aspx_cs"},
    {aspx_vb : "aspx_vb"},
    {asy : "Asymptote"},
    {basemake : "Makefile"},
    {bash : "Bash"},
    {bat : "Batchfile"},
    {bbcode : "BBCode"},
    {befunge : "Befunge"},
    {blitzmax : "BlitzMax"},
    {boo : "Boo"},
    {c : "C"},
    {c_objdump : "c_objdump"},
    {cfm : "Coldfusion HTML"},
    {cfs : "cfstatement"},
    {cheetah : "Cheetah"},
    {clojure : "Clojure"},
    {cmake : "CMake"},
    {coffee_script : "CoffeeScript"},
    {common_lisp : "Common Lisp"},
    {console : "Bash Session"},
    {control : "Debian Control file"},
    {cpp : "C++"},
    {cpp_objdump : "cpp_objdump"},
    {csharp : "C#"},
    {css : "CSS"},
    {css_django : "CSS+Django/Jinja"},
    {css_erb : "CSS+Ruby"},
    {css_genshitext : "CSS+Genshi Text"},
    {css_mako : "CSS+Mako"},
    {css_myghty : "CSS+Myghty"},
    {css_php : "CSS+PHP"},
    {css_smarty : "CSS+Smarty"},
    {cython : "Cython"},
    {d : "D"},
    {d_objdump : "d_objdump"},
    {delphi : "Delphi"},
    {diff : "Diff"},
    {django : "Django/Jinja"},
    {dpatch : "Darcs Patch"},
    {duel : "Duel"},
    {dylan : "Dylan"},
    {erb : "ERB"},
    {erl : "Erlang erl session"},
    {erlang : "Erlang"},
    {evoque : "Evoque"},
    {factor : "Factor"},
    {felix : "Felix"},
    {fortran : "Fortran"},
    {gas : "GAS"},
    {genshi : "Genshi"},
    {genshitext : "Genshi Text"},
    {glsl : "GLSL"},
    {gnuplot : "Gnuplot"},
    {go : "Go"},
    {gooddata_cl : "GoodData_CL"},
    {groff : "Groff"},
    {haml : "Haml"},
    {haskell : "Haskell"},
    {html : "HTML"},
    {html_cheetah : "HTML+Cheetah"},
    {html_django : "HTML+Django/Jinja"},
    {html_evoque : "HTML+Evoque"},
    {html_genshi : "HTML+Genshi"},
    {html_mako : "HTML+Mako"},
    {html_myghty : "HTML+Myghty"},
    {html_php : "HTML+PHP"},
    {html_smarty : "HTML+Smarty"},
    {html_velocity : "HTML+Velocity"},
    {hx : "haXe"},
    {hybris : "Hybris"},
    {ini : "INI"},
    {io : "Io"},
    {ioke : "Ioke"},
    {irc : "IRC logs"},
    {jade : "Jade"},
    {java : "Java"},
    {js : "JavaScript"},
    {js_cheetah : "JavaScript+Cheetah"},
    {js_django : "JavaScript+Django/Jinja"},
    {js_erb : "JavaScript+Ruby"},
    {js_genshitext : "JavaScript+Genshi Text"},
    {js_mako : "JavaScript+Mako"},
    {js_myghty : "JavaScript+Myghty"},
    {js_php : "JavaScript+PHP"},
    {js_smarty : "JavaScript+Smarty"},
    {jsp : "Java Server Page"},
    {lhs : "Literate Haskell"},
    {lighty : "Lighttpd configuration file"},
    {llvm : "LLVM"},
    {logtalk : "Logtalk"},
    {lua : "Lua"},
    {make : "Makefile"},
    {mako : "Mako"},
    {maql : "MAQL"},
    {mason : "Mason"},
    {matlab : "Matlab"},
    {matlabsession : "Matlab session"},
    {minid : "MiniD"},
    {modelica : "Modelica"},
    {modula2 : "Modula_2"},
    {moocode : "MOOCode"},
    {mupad : "MuPAD"},
    {mxml : "MXML"},
    {myghty : "Myghty"},
    {mysql : "MySQL"},
    {nasm : "NASM"},
    {newspeak : "Newspeak"},
    {nginx : "Nginx configuration file"},
    {numpy : "NumPy"},
    {objdump : "objdump"},
    {objective_c : "Objective_C"},
    {objective_j : "Objective_J"},
    {ocaml : "OCaml"},
    {ooc : "Ooc"},
    {perl : "Perl"},
    {php : "PHP"},
    {postscript : "PostScript"},
    {pot : "Gettext Catalog"},
    {pov : "POVRay"},
    {prolog : "Prolog"},
    {properties : "Properties"},
    {protobuf : "Protocol Buffer"},
    {py3tb : "Python 3.0 Traceback"},
    {pycon : "Python console session"},
    {pytb : "Python Traceback"},
    {python : "Python"},
    {python3 : "Python 3"},
    {ragel : "Ragel"},
    {ragel_c : "Ragel in C Host"},
    {ragel_cpp : "Ragel in CPP Host"},
    {ragel_d : "Ragel in D Host"},
    {ragel_em : "Embedded Ragel"},
    {ragel_java : "Ragel in Java Host"},
    {ragel_objc : "Ragel in Objective C Host"},
    {ragel_ruby : "Ragel in Ruby Host"},
    {raw : "Raw token data"},
    {rb : "Ruby"},
    {rbcon : "Ruby irb session"},
    {rconsole : "RConsole"},
    {rebol : "REBOL"},
    {redcode : "Redcode"},
    {rhtml : "RHTML"},
    {rst : "reStructuredText"},
    {sass : "Sass"},
    {scala : "Scala"},
    {scaml : "Scaml"},
    {scheme : "Scheme"},
    {scss : "SCSS"},
    {smalltalk : "Smalltalk"},
    {smarty : "Smarty"},
    {sourceslist : "Debian Sourcelist"},
    {splus : "S"},
    {sql : "SQL"},
    {sqlite3 : "sqlite3con"},
    {squidconf : "SquidConf"},
    {ssp : "Scalate Server Page"},
    {tcl : "Tcl"},
    {tcsh : "Tcsh"},
    {tex : "TeX"},
    {text : "Text only"},
    {trac_wiki : "MoinMoin/Trac Wiki markup"},
    {v : "verilog"},
    {vala : "Vala"},
    {vb_net : "VB.net"},
    {velocity : "Velocity"},
    {vim : "VimL"},
    {xml : "XML"},
    {xml_cheetah : "XML+Cheetah"},
    {xml_django : "XML+Django/Jinja"},
    {xml_erb : "XML+Ruby"},
    {xml_evoque : "XML+Evoque"},
    {xml_mako : "XML+Mako"},
    {xml_myghty : "XML+Myghty"},
    {xml_php : "XML+PHP"},
    {xml_smarty : "XML+Smarty"},
    {xml_velocity : "XML+Velocity"},
    {xquery : "XQuery"},
    {xslt : "XSLT"},
    {yaml : "YAML"},


];

module.exports = langs;
